
/home/isi-projets/sensorNanny/dev/vaimos/vaimoskai/codeC/

cc template.c ktime.c csv.c kuuid.c ktab.c kjson.c find.c makejson.c -luuid -o makejson 


./makejson /home/isi-projets/sensorNanny/data/vaimos/30mn-files/lognav_Wed_Jun_12_14h57min01sec_2013.csv /home/isi-projets/sensorNanny/data/vaimos/jsonOM/lognav_Wed_Jun_12_14h57min01sec_2013.json


clean: rm *.o


/home/isi-projets/sensorNanny/data/vaimos/orig-files






./makejson /home/isi-projets/sensorNanny/data/vaimos/30mn-files/41lognav_Thu_Aug_23_15h27min02sec_2012.csv  /home/isi-projets/sensorNanny/data/vaimos/jsonOM/41lognav_Thu_Aug_23_15h27min02sec_2012.json

./makejson /home/isi-projets/sensorNanny/data/vaimos/30mn-files/42lognav_Thu_Aug_23_15h27min02sec_2012.csv  /home/isi-projets/sensorNanny/data/vaimos/jsonOM/42lognav_Thu_Aug_23_15h27min02sec_2012.json

./makejson /home/isi-projets/sensorNanny/data/vaimos/30mn-files/43lognav_Thu_Aug_23_15h27min02sec_2012.csv  /home/isi-projets/sensorNanny/data/vaimos/jsonOM/43lognav_Thu_Aug_23_15h27min02sec_2012.json

./makejson /home/isi-projets/sensorNanny/data/vaimos/30mn-files/44lognav_Thu_Aug_23_15h27min02sec_2012.csv  /home/isi-projets/sensorNanny/data/vaimos/jsonOM/44lognav_Thu_Aug_23_15h27min02sec_2012.json

./makejson /home/isi-projets/sensorNanny/data/vaimos/30mn-files/45lognav_Thu_Aug_23_15h27min02sec_2012.csv  /home/isi-projets/sensorNanny/data/vaimos/jsonOM/45lognav_Thu_Aug_23_15h27min02sec_2012.json

./makejson /home/isi-projets/sensorNanny/data/vaimos/30mn-files/46lognav_Thu_Aug_23_15h27min02sec_2012.csv  /home/isi-projets/sensorNanny/data/vaimos/jsonOM/46lognav_Thu_Aug_23_15h27min02sec_2012.json

./makejson /home/isi-projets/sensorNanny/data/vaimos/30mn-files/47lognav_Thu_Aug_23_15h27min02sec_2012.csv  /home/isi-projets/sensorNanny/data/vaimos/jsonOM/47lognav_Thu_Aug_23_15h27min02sec_2012.json

./makejson /home/isi-projets/sensorNanny/data/vaimos/30mn-files/48lognav_Thu_Aug_23_15h27min02sec_2012.csv  /home/isi-projets/sensorNanny/data/vaimos/jsonOM/48lognav_Thu_Aug_23_15h27min02sec_2012.json

./makejson /home/isi-projets/sensorNanny/data/vaimos/30mn-files/49lognav_Thu_Aug_23_15h27min02sec_2012.csv  /home/isi-projets/sensorNanny/data/vaimos/jsonOM/49lognav_Thu_Aug_23_15h27min02sec_2012.json

./makejson /home/isi-projets/sensorNanny/data/vaimos/30mn-files/50lognav_Thu_Aug_23_15h27min02sec_2012.csv  /home/isi-projets/sensorNanny/data/vaimos/jsonOM/50lognav_Thu_Aug_23_15h27min02sec_2012.json






















./makejson /home/isi-projets/sensorNanny/data/vaimos/30mn-files/1lognav_Tue_Aug_21_18h44min01sec_2012.csv  /home/isi-projets/sensorNanny/data/vaimos/jsonOM/81lognav_Tue_Aug_21_18h44min01sec_2012.json

./makejson /home/isi-projets/sensorNanny/data/vaimos/30mn-files/2lognav_Tue_Aug_21_18h44min01sec_2012.csv  /home/isi-projets/sensorNanny/data/vaimos/jsonOM/82lognav_Tue_Aug_21_18h44min01sec_2012.json

./makejson /home/isi-projets/sensorNanny/data/vaimos/30mn-files/3lognav_Tue_Aug_21_18h44min01sec_2012.csv  /home/isi-projets/sensorNanny/data/vaimos/jsonOM/83lognav_Tue_Aug_21_18h44min01sec_2012.json

./makejson /home/isi-projets/sensorNanny/data/vaimos/30mn-files/4lognav_Tue_Aug_21_18h44min01sec_2012.csv  /home/isi-projets/sensorNanny/data/vaimos/jsonOM/84lognav_Tue_Aug_21_18h44min01sec_2012.json

./makejson /home/isi-projets/sensorNanny/data/vaimos/30mn-files/5lognav_Tue_Aug_21_18h44min01sec_2012.csv  /home/isi-projets/sensorNanny/data/vaimos/jsonOM/85lognav_Tue_Aug_21_18h44min01sec_2012.json

./makejson /home/isi-projets/sensorNanny/data/vaimos/30mn-files/86lognav_Tue_Aug_21_18h44min01sec_2012.csv  /home/isi-projets/sensorNanny/data/vaimos/jsonOM/86lognav_Tue_Aug_21_18h44min01sec_2012.json

./makejson /home/isi-projets/sensorNanny/data/vaimos/30mn-files/87lognav_Tue_Aug_21_18h44min01sec_2012.csv  /home/isi-projets/sensorNanny/data/vaimos/jsonOM/87lognav_Tue_Aug_21_18h44min01sec_2012.json

./makejson /home/isi-projets/sensorNanny/data/vaimos/30mn-files/88lognav_Tue_Aug_21_18h44min01sec_2012.csv  /home/isi-projets/sensorNanny/data/vaimos/jsonOM/88lognav_Tue_Aug_21_18h44min01sec_2012.json

./makejson /home/isi-projets/sensorNanny/data/vaimos/30mn-files/89lognav_Tue_Aug_21_18h44min01sec_2012.csv  /home/isi-projets/sensorNanny/data/vaimos/jsonOM/89lognav_Tue_Aug_21_18h44min01sec_2012.json











./makejson /home/isi-projets/sensorNanny/data/vaimos/30mn-files/lognav_Wed_Jun_12_10h10min02sec_2013.csv /home/isi-projets/sensorNanny/data/vaimos/jsonOM/lognav_Wed_Jun_12_10h10min02sec_2013.json

./makejson /home/isi-projets/sensorNanny/data/vaimos/30mn-files/lognav_Wed_Jun_12_14h41min02sec_2013.csv /home/isi-projets/sensorNanny/data/vaimos/jsonOM/lognav_Wed_Jun_12_14h41min02sec_2013.json

./makejson /home/isi-projets/sensorNanny/data/vaimos/30mn-files/lognav_Wed_Jun_12_14h57min01sec_2013.csv /home/isi-projets/sensorNanny/data/vaimos/jsonOM/lognav_Wed_Jun_12_14h57min01sec_2013.json

./makejson /home/isi-projets/sensorNanny/data/vaimos/30mn-files/0lognav_Wed_Jun_12_15h17min01sec_2013.csv /home/isi-projets/sensorNanny/data/vaimos/jsonOM/0lognav_Wed_Jun_12_15h17min01sec_2013.json

./makejson /home/isi-projets/sensorNanny/data/vaimos/30mn-files/1lognav_Wed_Jun_12_15h17min01sec_2013.csv /home/isi-projets/sensorNanny/data/vaimos/jsonOM/1lognav_Wed_Jun_12_15h17min01sec_2013.json

./makejson /home/isi-projets/sensorNanny/data/vaimos/30mn-files/2lognav_Wed_Jun_12_15h17min01sec_2013.csv /home/isi-projets/sensorNanny/data/vaimos/jsonOM/2lognav_Wed_Jun_12_15h17min01sec_2013.json
